#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename

#SBATCH --time=15:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node 
#SBATCH --mem=120G   # maximum memory per node
#SBATCH --job-name="ensemble_wtmean"
#SBATCH --mail-user=@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output="out_ensemble_wtmean" # job standard output file (%j replaced by job id)
#SBATCH --error="err_ensemble_wtmean" # job standard error file (%j replaced by job id)

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

module load r
R CMD BATCH ensemble_wtmean.R ensemble_wtmean.Log
